CREATE TABLE public.Services (
  ID VARCHAR NOT NULL,
  NAME VARCHAR NOT NULL,
  URI VARCHAR NOT NULL,
  MAXTIMEOUT BIGINT NOT NULL
);

CREATE TABLE public.HealthCheckResult (
  ID VARCHAR NOT NULL,
  TIME TIMESTAMP NOT NULL,
  RESPONSETIME BIGINT NOT NULL,
  CODE INTEGER NOT NULL,
  BODY VARCHAR NOT NULL
);
